=== dotnet/linker/src/ILLink.Shared/ILLink.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema attributeFormDefault="unqualified"
		elementFormDefault="unqualified"
		xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	
	<xsd:element name="method">
		<xsd:complexType>
			<xsd:choice maxOccurs="unbounded" minOccurs="0">
				<xsd:element ref="attribute" />
				<xsd:element name="parameter">
					<xsd:complexType>
						<xsd:choice minOccurs="0" maxOccurs="unbounded">
							<xsd:element ref="attribute" />
						</xsd:choice>
						<xsd:attribute name="name" />
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="return">
					<xsd:complexType>
						<xsd:choice maxOccurs="unbounded" minOccurs="0">
							<xsd:element ref="attribute" />
						</xsd:choice>
					</xsd:complexType>
				</xsd:element>
			</xsd:choice>
			<xsd:attribute name="name" type="xsd:string" />
			<xsd:attribute name="signature" type="xsd:string" />
			<xsd:attribute name="required" type="xsd:boolean" />
			<xsd:attribute name="body" type="xsd:string" />
			<xsd:attribute name="value" type="xsd:string" />
			<xsd:attribute name="feature" />
			<xsd:attribute name="featurevalue" type="xsd:boolean" />
			<xsd:attribute name="featuredefault" type="xsd:boolean" />
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="event">
		<xsd:complexType>
			<xsd:attribute name="name" type="xsd:string" />
			<xsd:attribute name="signature" type="xsd:string" />
			<xsd:attribute name="feature" />
			<xsd:attribute name="featurevalue" type="xsd:boolean" />
			<xsd:attribute name="featuredefault" type="xsd:boolean" />
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="field">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element minOccurs="0" maxOccurs="unbounded" ref="attribute" />
			</xsd:sequence>
			<xsd:attribute name="name" type="xsd:string" />
			<xsd:attribute name="signature" type="xsd:string" />
			<xsd:attribute name="value" type="xsd:string" />
			<xsd:attribute name="initialize" type="xsd:string" />
			<xsd:attribute name="required" type="xsd:boolean" />
			<xsd:attribute name="feature" />
			<xsd:attribute name="featurevalue" type="xsd:boolean" />
			<xsd:attribute name="featuredefault" type="xsd:boolean" />
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="property">
		<xsd:complexType>
			<xsd:choice maxOccurs="unbounded" minOccurs="0">
				<xsd:element ref="attribute" />
			</xsd:choice>
			<xsd:attribute name="name" type="xsd:string"/>
			<xsd:attribute name="signature" type="xsd:string" />
			<xsd:attribute name="required" type="xsd:boolean" />
			<xsd:attribute name="accessors" type="accessorvalues" />
			<xsd:attribute name="type" type="xsd:string" />
			<xsd:attribute name="feature" />
			<xsd:attribute name="featurevalue" type="xsd:boolean" />
			<xsd:attribute name="featuredefault" type="xsd:boolean" />
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="resource">
		<xsd:complexType>
			<xsd:attribute name="name" use="required" />
			<xsd:attribute name="action" use="required" />
			<xsd:attribute name="featurevalue" type="xsd:boolean" />
			<xsd:attribute name="featuredefault" type="xsd:boolean" />
			<xsd:attribute name="feature" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="argument">
		<xsd:complexType mixed="true">
			<xsd:choice minOccurs="0" maxOccurs="1">
				<xsd:element name="argument">
					<xsd:complexType>
						<xsd:simpleContent>
							<xsd:extension base="xsd:string">
								<xsd:attribute name="type" />
							</xsd:extension>
						</xsd:simpleContent>
					</xsd:complexType>
				</xsd:element>
			</xsd:choice>
			<xsd:attribute name="type" />
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="attribute">
		<xsd:complexType>
			<xsd:choice maxOccurs="unbounded" minOccurs="0">
				<xsd:element ref="argument" />
				<xsd:element minOccurs="0" maxOccurs="unbounded" name="property">
					<xsd:complexType>
						<xsd:simpleContent>
							<xsd:extension base="xsd:string">
								<xsd:attribute name="name" />
							</xsd:extension>
						</xsd:simpleContent>
					</xsd:complexType>
				</xsd:element>
			</xsd:choice>
			<xsd:attribute name="internal" type="xsd:string" />
			<xsd:attribute name="fullname" type="xsd:string" />
			<xsd:attribute name="assembly" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="namespace">
		<xsd:complexType>
			<xsd:attribute name="fullname"/>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="assembly">
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element minOccurs="0" maxOccurs="unbounded" ref="type" />
				<xsd:element minOccurs="0" maxOccurs="unbounded" ref="attribute" />
				<xsd:element minOccurs="0" maxOccurs="unbounded" ref="resource" />
				<xsd:element minOccurs="0" maxOccurs="unbounded" ref="namespace" />
			</xsd:choice>
			<xsd:attribute name="fullname" type="xsd:string" use="required" />
			<xsd:attribute name="feature" />
			<xsd:attribute name="featurevalue" type="xsd:boolean" />
			<xsd:attribute name="featuredefault" type="xsd:boolean" />
			<xsd:attribute name="preserve" type="preservevalues" />
		</xsd:complexType>
	</xsd:element>
	
	<xsd:simpleType name="preservevalues">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="all" />
			<xsd:enumeration value="none" />
			<xsd:enumeration value="fields" />
			<xsd:enumeration value="methods" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="accessorvalues">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="all" />
			<xsd:enumeration value="get" />
			<xsd:enumeration value="set" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:element name="type">
		<xsd:complexType>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element ref="event" />
				<xsd:element ref="method" />
				<xsd:element ref="attribute" />
				<xsd:element ref="field" />
				<xsd:element ref="property" />
				<xsd:element ref="type" />
			</xsd:choice>
			<xsd:attribute name="fullname" type="xsd:string" />
			<xsd:attribute name="name" type="xsd:string" />
			<xsd:attribute name="required" type="xsd:boolean" />
			<xsd:attribute name="preserve" type="preservevalues" />
			<xsd:attribute name="feature" type="xsd:string" />
			<xsd:attribute name="featurevalue" type="xsd:boolean" />
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="linker">
		<xsd:complexType>
			<xsd:choice maxOccurs="unbounded" minOccurs="0">
				<xsd:element ref="assembly" />
				<xsd:element ref="type" />
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>
	
</xsd:schema>

=== dotnet/linker/test/Mono.Linker.Tests.Cases/LinkXml/UnusedMethodPreservedByLinkXmlIsKept.xml
<linker xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://www.w3schools.com ../../../src/ILLink.Shared/ILLink.xsd">
  <assembly fullname="test, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null">
    <type fullname="Mono.Linker.Tests.Cases.LinkXml.UnusedMethodPreservedByLinkXmlIsKept/Unused">
      <method signature="System.Void PreservedMethod()" />
      <method signature="System.Void PreservedMethod2(System.Int32,System.String)" />
      <method name="PreservedMethod3" />
      <method signature="System.Void PreservedMethod4(System.Collections.Generic.List`1&lt;System.Int32&gt;)" />
      <method signature="System.Void PreservedMethod5(T)" />
    </type>
  </assembly>
</linker>
