=== dotnet/linker/src/ILLink.Shared/ILLink.LinkAttributes.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema attributeFormDefault="unqualified"
		elementFormDefault="unqualified"
		xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:complexType name="typechild">
		<xsd:choice maxOccurs="unbounded" minOccurs="0">
			<xsd:element ref="attribute"></xsd:element>
		</xsd:choice>
		<xsd:attribute name="feature" />
		<xsd:attribute name="featurevalue" type="xsd:boolean" />
		<xsd:attribute name="featuredefault" type="xsd:boolean" />
		<xsd:attribute name="name" />
		<xsd:attribute name="signature" />
	</xsd:complexType>
	
	<xsd:element name="method">
		<xsd:complexType>
			<xsd:complexContent>
				<xsd:extension base="typechild">
					<xsd:choice maxOccurs="unbounded" minOccurs="0">
						<xsd:choice maxOccurs="unbounded" minOccurs="0">
							<xsd:element name="parameter">
								<xsd:complexType>
									<xsd:choice maxOccurs="unbounded" minOccurs="0">
										<xsd:element ref="attribute"></xsd:element>
									</xsd:choice>
									<xsd:attribute name="name" />
								</xsd:complexType>
							</xsd:element>
						</xsd:choice>
						<xsd:choice maxOccurs="1" minOccurs="0">
							<xsd:element name="return">
								<xsd:complexType>
									<xsd:choice maxOccurs="unbounded" minOccurs="0">
										<xsd:element ref="attribute"></xsd:element>
									</xsd:choice>
								</xsd:complexType>
							</xsd:element>
						</xsd:choice>
					</xsd:choice>
				</xsd:extension>
			</xsd:complexContent>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="event">
		<xsd:complexType>
			<xsd:complexContent>
				<xsd:extension base="typechild" />
			</xsd:complexContent>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="field">
		<xsd:complexType>
			<xsd:complexContent>
				<xsd:extension base="typechild" />
			</xsd:complexContent>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="property">
		<xsd:complexType>
			<xsd:complexContent>
				<xsd:extension base="typechild" />
			</xsd:complexContent>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="argument">
		<xsd:complexType mixed="true">
			<xsd:choice minOccurs="0" maxOccurs="1">
				<xsd:element name="argument" type="xsd:string"/>
			</xsd:choice>
			<xsd:attribute name="type" />
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="attribute">
		<xsd:complexType>
			<xsd:choice maxOccurs="unbounded" minOccurs="0">
				<xsd:element ref="argument" />
				<xsd:element minOccurs="0" maxOccurs="unbounded" name="property">
					<xsd:complexType mixed="true">
						<xsd:choice maxOccurs="unbounded" minOccurs="0">
							<xsd:element ref="attribute"></xsd:element>
						</xsd:choice>
						<xsd:attribute name="name" />
					</xsd:complexType>
				</xsd:element>
			</xsd:choice>
			<xsd:attribute name="internal" type="xsd:string" />
			<xsd:attribute name="fullname" type="xsd:string" />
			<xsd:attribute name="assembly" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="namespace">
		<xsd:complexType>
			<xsd:attribute name="fullname"/>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="assembly">
		<xsd:complexType>
			<xsd:choice maxOccurs="unbounded" minOccurs="0">
				<xsd:element ref="attribute" />
				<xsd:element ref="type" />
				<xsd:element ref="namespace" />
			</xsd:choice>
			<xsd:attribute name="fullname" type="xsd:string" use="required" />
			<xsd:attribute name="name" />
			<xsd:attribute name="signature" />
			<xsd:attribute name="feature" />
			<xsd:attribute name="featurevalue" type="xsd:boolean" />
			<xsd:attribute name="featuredefault" type="xsd:boolean" />
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="type">
		<xsd:complexType>
			<xsd:choice maxOccurs="unbounded" minOccurs="0">
				<xsd:element ref="attribute"></xsd:element>
				<xsd:element ref="event" />
				<xsd:element ref="method" />
				<xsd:element ref="field" />
				<xsd:element ref="property" />
				<xsd:element name="type">
					<xsd:complexType>
						<xsd:choice minOccurs="0" maxOccurs="unbounded">
							<xsd:element ref="event" />
							<xsd:element ref="method" />
							<xsd:element ref="field" />
							<xsd:element ref="property" />
							<xsd:element ref="attribute"></xsd:element>
						</xsd:choice>
						<xsd:attribute name="name" type="xsd:string" />
						<xsd:attribute name="feature" />
						<xsd:attribute name="featurevalue" type="xsd:boolean" />
						<xsd:attribute name="featuredefault" type="xsd:boolean" />
					</xsd:complexType>
				</xsd:element>
			</xsd:choice>
			<xsd:attribute name="feature" />
			<xsd:attribute name="featurevalue" type="xsd:boolean" />
			<xsd:attribute name="featuredefault" type="xsd:boolean" />
			<xsd:attribute name="fullname" type="xsd:string" use="required"/>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="linker">
		<xsd:complexType>
			<xsd:choice maxOccurs="unbounded" minOccurs="0">
				<xsd:element ref="assembly" />
				<xsd:element ref="type" />
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>
	
</xsd:schema>

=== dotnet/linker/test/Mono.Linker.Tests.Cases/UnreachableBlock/InstanceMethodSubstitutions.xml
<linker xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://www.w3schools.com ..\..\..\src\ILLink.Shared\ILLink.LinkAttributes.xsd">
  <assembly fullname="test, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null">
    <type fullname="Mono.Linker.Tests.Cases.UnreachableBlock.InstanceMethodSubstitutions">
      <method signature="System.Boolean IsEnabled()" body="stub" value="false">
      </method>
    </type>
    <type fullname="Mono.Linker.Tests.Cases.UnreachableBlock.InstanceMethodSubstitutions/TestVirtualMethodBase">
      <method signature="System.Boolean IsEnabled()" body="stub" value="true">
      </method>
    </type>
    <type fullname="Mono.Linker.Tests.Cases.UnreachableBlock.InstanceMethodSubstitutions/TestVirtualMethodType">
      <method signature="System.Boolean IsEnabled()" body="stub" value="true">
      </method>
    </type>
  </assembly>
</linker>

=== dotnet/linker/test/Mono.Linker.Tests.Cases/DynamicDependencies/DynamicDependencyFromAttributeXml.mono.Attributes.xml
<?xml version="1.0" encoding="utf-8" ?>
<linker xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://www.w3schools.com ..\..\..\src\ILLink.Shared\ILLink.LinkAttributes.xsd">
	<assembly fullname="test, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null">
		<type fullname="Mono.Linker.Tests.Cases.DynamicDependencies.DynamicDependencyFromAttributeXml">
			<method name="DependencyToUnusedMethod">
				<attribute fullname="System.Diagnostics.CodeAnalysis.DynamicDependencyAttribute" assembly="Mono.Linker.Tests.Cases.Expectations">
					<argument>UnusedMethod</argument>
				</attribute>
			</method>
			<method name="DependencyToUnusedType">
				<attribute fullname="System.Diagnostics.CodeAnalysis.DynamicDependencyAttribute" assembly="Mono.Linker.Tests.Cases.Expectations">
					<argument type="System.Diagnostics.CodeAnalysis.DynamicallyAccessedMemberTypes, test">All</argument>
					<argument type="System.Type">Mono.Linker.Tests.Cases.DynamicDependencies.DynamicDependencyFromAttributeXml/NonUsedType</argument>
				</attribute>
			</method>
		</type>
	</assembly>
</linker>

=== dotnet/linker/test/Mono.Linker.Tests.Cases/LinkXml/EmbeddedLinkXmlUnresolvedReferencesAreReported.xml
<linker xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://www.w3schools.com ..\..\..\src\ILLink.Shared\ILLink.LinkAttributes.xsd">
  <assembly fullname="test, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null">
    <type fullname="UnknownType" />
    <type fullname="Mono.Linker.Tests.Cases.LinkXml.EmbeddedLinkXmlUnresolvedReferencesAreReported/TestType" >
      <!-- The type has "System.Int32 FieldWithSignature"-->
      <field signature="System.String FieldWithSignature" />
      <field signature="System.Int32 FieldWithSignature" />
      <field name="UnknownField" />

      <!-- The type has "System.String MethodWithSignature()" -->
      <method signature="System.Void MethodWithSignature()" />
      <method signature="System.String MethodWithSignature()" />
      <method name="UnknownMethod" />

      <!-- The type has "System.EventHandler EventWithSignature" -->
      <event signature="System.ResolveEventHandler EventWithSignature" />
      <event signature="System.EventHandler EventWithSignature" />
      <event name="UnknownEvent" />

      <!-- The type has "System.Int32 PropertyWithSignature"-->
      <property signature="System.String PropertyWithSignature" />
      <property signature="System.Int32 PropertyWithSignature" />
      <property name="UnknownProperty" />
    </type>
    <namespace fullname="UnknownNamespace" />
  </assembly>
</linker>

=== dotnet/linker/test/Mono.Linker.Tests.Cases/LinkXml/PreserveIndividualMembersOfNonRequiredType.xml
<linker xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://www.w3schools.com ..\..\..\src\ILLink.Shared\ILLink.LinkAttributes.xsd">
  <assembly fullname="test, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null">
    <type fullname="Mono.Linker.Tests.Cases.LinkXml.PreserveIndividualMembersOfNonRequiredType/Required" required="false">
      <field name="Field1" />
      <method name="Method1" />
      <property name="Property1" />
      <event name="Event1" />
      <method name=".ctor" />
    </type>
  </assembly>
</linker>

=== dotnet/linker/test/Mono.Linker.Tests.Cases/LinkAttributes/LinkerAttributeRemovalConditional.xml
<?xml version="1.0" encoding="utf-8" ?>
<linker xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://www.w3schools.com ..\..\..\src\ILLink.Shared\ILLink.LinkAttributes.xsd">
  <assembly fullname="test">
    <type fullname="Mono.Linker.Tests.Cases.LinkAttributes.TestConditionalRemoveAttribute">
      <attribute internal="RemoveAttributeInstances">
        <argument type="System.Object">
          <argument>remove1</argument>
        </argument>
      </attribute>
    </type>
    <type fullname="Mono.Linker.Tests.Cases.LinkAttributes.TestConditionalRemoveAttribute">
      <attribute internal="RemoveAttributeInstances">
        <argument type="System.Object">
          <argument type="System.Int32">100</argument>
        </argument>
      </attribute>
    </type>
    <type fullname="Mono.Linker.Tests.Cases.LinkAttributes.TestConditionalRemoveAttribute">
      <attribute internal="RemoveAttributeInstances">
        <argument type="System.Object">
          <argument>remove0</argument>
        </argument>
      </attribute>
    </type>
  </assembly>
</linker>
